#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# When
#
# Copyright (c) 2015 Francesco Garosi
# Released under the BSD License (see LICENSE.md)
#
# Small startup applet that runs tasks when particular conditions are met.
# NOTE: This is a stub script that loads the main when-command applet.

from importlib.machinery import SourceFileLoader

_m = SourceFileLoader("when_command",
                      "/usr/share/when-command/when-command.py").load_module()

# make all loaded module symbols top level
for _attr in dir(_m):
    if not attr.startswith('_'):
        globals()[_attr] = getattr(_m, _attr)
main()

# end.
