#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# When
#
# Copyright (c) 2015 Francesco Garosi
# Released under the BSD License (see LICENSE.md)
#
# Small startup applet that runs tasks when particular conditions are met.
# NOTE: This is a stub script that loads the main when-command applet.


from importlib.machinery import SourceFileLoader


_m = SourceFileLoader("when_command",
                      "/usr/share/when-command/when-command.py").load_module()

# bring pickleable objects to top level
Resources = _m.Resources
Tasks = _m.Tasks
Conditions = _m.Conditions
SignalHandlers = _m.SignalHandlers
Task = _m.Task
Condition = _m.Condition
IntervalBasedCondition = _m.IntervalBasedCondition
TimeBasedCondition = _m.TimeBasedCondition
CommandBasedCondition = _m.CommandBasedCondition
IdleTimeBasedCondition = _m.IdleTimeBasedCondition
EventBasedCondition = _m.EventBasedCondition
PathNotifyBasedCondition = _m.PathNotifyBasedCondition
SignalHandler = _m.SignalHandler

# run the applet module entry point
_m.main()


# end.
